accueil:
    path:    /
    defaults:  
        _controller: CoreBundle:Partie:index 

partie:
    path:    /partie/{id}
    defaults:
        _controller: CoreBundle:Partie:partie
    requirements:
        id: \d+
        
add_partie:
    path:    /addPartie/{nb}
    defaults:
        _controller: CoreBundle:Partie:add
    requirements:
        nb: \d+
